general.import = [ "~/.config/soshoku/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[terminal.shell]
program = "zsh"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.9

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]